version: "3.8"
services:
  db:
    container_name: "auditor-app-db"
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "auditor_app_db"
      POSTGRES_USER: "auditor_app"
      POSTGRES_PASSWORD: "secret"
